export type BodyStyleType = '4x4'
    | 'city-car'
    | 'convertible'
    | 'coupe'
    | 'estate'
    | 'executive'
    | 'hatchback'
    | 'hot-hatch'
    | 'hybridev'
    | 'large-suv'
    | 'luxury'
    | 'mpv'
    | 'saloon'
    | 'small-suv'
    | 'sports'
    | 'supermini'
    | 'van'
    | 'wagon'
